### ISSUE TITLE
 <x-smart-image src="http://shop.loc/storage/images/2021/12/07/88aaa8f34822c087065d7e0a2b55de210dd7ac0a.JPG" width="600px" />

### ISSUE THREAD

**Issue by rudaovel** [dietercoopman/smart#7]
syntax error, unexpected '=>' (T_DOUBLE_ARROW) (View: C:\OpenServer\domains\shop.loc\vendor\dietercoopman\smart\resources\views\components\smart-image.blade.php)
C:\OpenServer\domains\shop.loc\vendor\dietercoopman\smart\src\Factories\HtmlFactory.php#12
Facade\Ignition\Exceptions\ViewException
syntax error, unexpected '=>' (T_DOUBLE_ARROW)
C:\OpenServer\domains\shop.loc\vendor\dietercoopman\smart\src\Factories\HtmlFactory.php#12

**Comment by dietercoopman** [comment]
Hi @rudaovel could you please provide some extra information ? What version of php is your application running and which version of Laravel ? 

Thx

**Comment by dietercoopman** [comment]
Hi , i've done a fix for php 7.x , the package used a Php8 match syntax.

Could you please confirm that it works now 

Thx , and have a nice day !

**Comment by rudaovel** [comment]
> Hi @rudaovel could you please provide some extra information ? What version of php is your application running and which version of Laravel ?
> 
> Thx

Hello! php 7.4, laravel 8

**Comment by rudaovel** [comment]
> Hi , i've done a fix for php 7.x , the package used a Php8 match syntax.
> 
> Could you please confirm that it works now
> 
> Thx , and have a nice day !
view: <x-smart-image src="{{ storage_path('Screenshot_4.jpg') }}"  width="400px"/>

update package: "dietercoopman/smart": "dev-main",

syntax error, unexpected '|', expecting ';' or '{' (View: C:\OpenServer\domains\shop.loc\vendor\dietercoopman\smart\resources\views\components\smart-image.blade.php)
C:\OpenServer\domains\shop.loc\vendor\dietercoopman\smart\src\Factories\ImageTag.php#39
Facade\Ignition\Exceptions\ViewException
syntax error, unexpected '|', expecting ';' or '{'
C:\OpenServer\domains\shop.loc\vendor\dietercoopman\smart\src\Factories\ImageTag.php#39

**Comment by dietercoopman** [comment]
@rudaovel , I've tested it myself on php7.4 , and made it compatible with 7.4 , I had the same errors , they are now fixed 
can you confirm that please ?

**Comment by rudaovel** [comment]
> @rudaovel , I've tested it myself on php7.4 , and made it compatible with 7.4 , I had the same errors , they are now fixed can you confirm that please ?

Good afternoon! Now it has worked, but there is an error in loading the cached image, Photo screenshots below the links.

[https://drive.google.com/file/d/1A6VSFhVMtlsL6C0YZg2ZjddBYpebdMn3/view?usp=sharing](url)
[https://drive.google.com/file/d/1dJN_bad2j03qaekabE3CGf8et-tz0Ode/view?usp=sharing](url)

**Comment by dietercoopman** [comment]
Hi , it was extremely hard to figure it out but I've found it ! The path to the images generated by smart was relative to your products page , and the router couldn't resolve the path ... After some try and error I could simulate the problem and fix it.

Thank you very much for your patience and you're feedback , this is extreme valuable input 👍

**Comment by rudaovel** [comment]
> Hi , it was extremely hard to figure it out but I've found it ! The path to the images generated by smart was relative to your products page , and the router couldn't resolve the path ... After some try and error I could simulate the problem and fix it.
> 
> Thank you very much for your patience and your feedback , this is extreme valuable input 👍

Good evening! Thank you for your hard work, unfortunately it didn't solve my problem.

[https://drive.google.com/file/d/1_d1m2uvFDBZC01am2GpY-JojYabYRg3d/view?usp=sharing](https://drive.google.com/file/d/1_d1m2uvFDBZC01am2GpY-JojYabYRg3d/view?usp=sharing)

**Comment by dietercoopman** [comment]
I made the problem bigger,  I reverted the last commit , can you update please ... I think it might be a browser cache issue , can you please test it by disabling the cache in the network tab of chrome.

I've tested it with a public hosted file on github , with a file in my storage folder and a file in the public folder of my test project , and it works after clearing the browser cache.

The path to the images is generated automatically in the service provider of the package 

```php
 $this->app['router']->get('/smart/{filename}', [
            'uses' => 'Dietercoopman\Smart\Factories\ImageTag@serve',
            'as' => 'images',
        ])->where(['imagTag' => $filename_pattern]);
```

**Comment by dietercoopman** [comment]
I've tested it on php7.4, 8.0 and 8.1 👀

**Comment by rudaovel** [comment]
> I've tested it on php7.4, 8.0 and 8.1 👀

Hi! Thanks , it worked when I added /
` return '/smart/' . $src;`

**Comment by dietercoopman** [comment]
Ok great , can you pull request it if do you want to fix it myself ?

**Comment by rudaovel** [comment]
> added /

https://github.com/dietercoopman/smart/pull/14
